name: ShellScript CI

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check syntax
        run: bash -n test/test.sh

      - name: Run script (simulated input)
        run: |
          echo -e "hello\nbye" | ./test/test.sh
